//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VegeMoteur.App.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class CalibrageCale
    {
        public int CaleId { get; set; }
        public int CalibragId { get; set; }
        public Nullable<double> MesureA { get; set; }
        public Nullable<double> MesureB { get; set; }
        public Nullable<double> EcartA { get; set; }
        public Nullable<double> EcartB { get; set; }
        public Nullable<double> Emax { get; set; }
    
        public virtual Cale Cale { get; set; }
        public virtual ErreurContactPleineTouche ErreurContactPleineTouche { get; set; }
    }
}
