//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VegeMoteur.App.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VegeMoteurDBEntities : DbContext
    {
        public VegeMoteurDBEntities()
            : base("name=VegeMoteurDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cale> Cales { get; set; }
        public virtual DbSet<CalendrierCalibrage> CalendrierCalibrages { get; set; }
        public virtual DbSet<InstrumentGeneral> InstrumentGenerals { get; set; }
        public virtual DbSet<InstrumentSpecifique> InstrumentSpecifiques { get; set; }
        public virtual DbSet<Marque> Marques { get; set; }
        public virtual DbSet<Norme> Normes { get; set; }
        public virtual DbSet<PosteTravail> PosteTravails { get; set; }
        public virtual DbSet<Section> Sections { get; set; }
        public virtual DbSet<CalibrageCale> CalibrageCales { get; set; }
        public virtual DbSet<ErreurContactPartiel> ErreurContactPartiels { get; set; }
        public virtual DbSet<ErreurContactPleineTouche> ErreurContactPleineTouches { get; set; }
        public virtual DbSet<Position> Positions { get; set; }
        public virtual DbSet<Verification> Verifications { get; set; }
        public virtual DbSet<VerificationPosition> VerificationPositions { get; set; }
    }
}
