//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VegeMoteur.App.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ErreurContactPleineTouche
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ErreurContactPleineTouche()
        {
            this.CalibrageCales = new HashSet<CalibrageCale>();
        }
    
        public int Id { get; set; }
        public string Description { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<double> CaleMax { get; set; }
        public Nullable<double> Emax { get; set; }
        public int VerificationId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CalibrageCale> CalibrageCales { get; set; }
        public virtual Verification Verification { get; set; }
    }
}
