//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VegeMoteur.App.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class InstrumentSpecifique
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InstrumentSpecifique()
        {
            this.CalendrierCalibrages = new HashSet<CalendrierCalibrage>();
            this.Normes = new HashSet<Norme>();
            this.Verifications = new HashSet<Verification>();
        }
    
        public int Id { get; set; }
        public string Code { get; set; }
        public double Precision { get; set; }
        public string Type { get; set; }
        public Nullable<double> EtenduMax { get; set; }
        public Nullable<double> EtenduMin { get; set; }
        public string Unite { get; set; }
        public string Caractere { get; set; }
        public double Resolution { get; set; }
        public int FrequenceCalibrage { get; set; }
        public Nullable<int> FrequenceEtallonage { get; set; }
        public Nullable<System.DateTime> DateMiseEnService { get; set; }
        public int PostTravailId { get; set; }
        public int InstrumentGeneralId { get; set; }
        public int MarqueId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CalendrierCalibrage> CalendrierCalibrages { get; set; }
        public virtual InstrumentGeneral InstrumentGeneral { get; set; }
        public virtual Marque Marque { get; set; }
        public virtual PosteTravail PosteTravail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Norme> Normes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Verification> Verifications { get; set; }
    }
}
