//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VegeMoteur.App.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Norme
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Norme()
        {
            this.Cales = new HashSet<Cale>();
        }
    
        public int Id { get; set; }
        public string CodeNorme { get; set; }
        public int NombrePosition { get; set; }
        public bool Actuelle { get; set; }
        public int InstrumentSpecifiqueId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cale> Cales { get; set; }
        public virtual InstrumentSpecifique InstrumentSpecifique { get; set; }
    }
}
