//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VegeMoteur.App.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class VerificationPosition
    {
        public int PositionId { get; set; }
        public int VerificationId { get; set; }
        public Nullable<double> Mesure1 { get; set; }
        public Nullable<double> Mesure2 { get; set; }
        public Nullable<double> Ecart1 { get; set; }
        public Nullable<double> Ecart2 { get; set; }
    
        public virtual ErreurContactPartiel ErreurContactPartiel { get; set; }
        public virtual Position Position { get; set; }
    }
}
